### ISSUE TITLE
sklern's ValueError in report_metrics

### ISSUE THREAD

**Issue by yasunorikogure** [smshuai/DriverPower#12]
I found the error below occurs even when I use sample dataset.
How can I fix it? Thank you very much.
```
+ driverpower infer --feature /home/kogu/analysis/driverpower/hdf5/train_feature.hdf5 --response /home/kogu/analysis/driverpower/output/test_DP102/resource/test_DP102_test_y.tsv --model /home/kogu/analysis/driverpower/output/test_DP102/resource/test_DP102.GBM.model.pkl --method auto --name test_DP102 --outDir /home/kogu/analysis/driverpower/output/test_DP102
Traceback (most recent call last):
  File "/home/kogu/.local/bin/driverpower", line 11, in <module>
    load_entry_point('DriverPower==1.0.1', 'console_scripts', 'driverpower')()
  File "/home/kogu/.local/lib/python3.6/site-packages/DriverPower-1.0.1-py3.6.egg/driverpower/interface.py", line 147, in main
  File "/home/kogu/.local/lib/python3.6/site-packages/DriverPower-1.0.1-py3.6.egg/driverpower/infer.py", line 94, in make_inference
  File "/home/kogu/.local/lib/python3.6/site-packages/DriverPower-1.0.1-py3.6.egg/driverpower/model.py", line 301, in report_metrics
  File "/usr/local/package/python/3.6.4/lib/python3.6/site-packages/sklearn/metrics/regression.py", line 530, in r2_score
    y_true, y_pred, multioutput)
  File "/usr/local/package/python/3.6.4/lib/python3.6/site-packages/sklearn/metrics/regression.py", line 76, in _check_reg_targets
    y_true = check_array(y_true, ensure_2d=False)
  File "/usr/local/package/python/3.6.4/lib/python3.6/site-packages/sklearn/utils/validation.py", line 462, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.
```

**Comment by yasunorikogure** [comment]
Sorry I found it was just a typo... `train_feature` and `test_feature.`
